// Real glyph-metric text measurement for card generators.
//
// Loads per-glyph advance widths extracted from the embedded WOFF2 fonts
// (same files the SVGs embed) so wrap/fit decisions match what a browser will
// actually render. The metrics JSON is generated by
// `compiler/export-font-metrics.py` (see its header) and committed under
// `generated/models/font-metrics.json`.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..', '..', '..');
const METRICS_FILE = path.join(ROOT, 'generated', 'models', 'font-metrics.json');

let cachedMetrics = null;

function loadMetrics() {
  if (cachedMetrics === null) {
    if (!fs.existsSync(METRICS_FILE)) {
      throw new Error(
        `Font metrics not found: ${METRICS_FILE}. Run \`python3 compiler/export-font-metrics.py\` in the design repo root (requires fonttools + brotli).`
      );
    }
    cachedMetrics = JSON.parse(fs.readFileSync(METRICS_FILE, 'utf-8'));
  }
  return cachedMetrics;
}

function getFont(familyKey) {
  const metrics = loadMetrics();
  const font = metrics[familyKey];
  if (!font) {
    throw new Error(`No font metrics for family key: ${familyKey}`);
  }
  return font;
}

// Measured advance width of a string in em units (1em = 1 font-size).
// Unknown glyphs fall back to the font's average advance so missing cmap
// entries cannot silently produce overflow.
function measureEm(font, text) {
  const { unitsPerEm, advances, cmap } = font;
  let knownTotal = 0;
  let knownCount = 0;
  for (const a of advances) {
    if (a > 0) {
      knownTotal += a;
      knownCount += 1;
    }
  }
  const avgAdvance = knownCount > 0 ? knownTotal / knownCount : 0.5 * unitsPerEm;

  let total = 0;
  for (const ch of String(text)) {
    const code = ch.codePointAt(0);
    const glyph = cmap[String(code)];
    total += glyph === undefined ? avgAdvance : advances[glyph];
  }
  return total / unitsPerEm;
}

// Width in px for a given font size.
function measurePx(font, text, fontSize) {
  return measureEm(font, text) * fontSize;
}

module.exports = { loadMetrics, getFont, measureEm, measurePx };
